swagger: '2.0'
info:
  version: "1.1.0"
  title: Project Artemis
  description: collector + feature toggle
host: interact.com
basePath: /api
produces:
  - application/json
paths:
  /event/oninit:
    post:
      parameters:
        - name: initInformation
          in: body
          required: true
          schema:
            $ref: "#/definitions/InitInformation"
      responses:
        200:
          description: Success
          schema:
            type: object
            required:
            - featureList
            - initCode
            properties:
              featureList:
                type: array
                description: List of features with version to render
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: feature name
                    version:
                      type: string
                      description: feature version to render
              deviceCode:
                type: string
              initCode:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onload:
    post:
      summary: Get config for client side and collecting OnLoad event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
            required:
              - customerCode
              - eventData
            properties:
              customerCode:
                type: string
                description: customer code
              hashedUserId:
                type: string
                description: hashed user id (unique)
              eventData:
                type: object
                description: data from browser onload event
                properties:
                  appCodeName:
                    type: string
                  appName:
                    type: string
                  appVersion:
                    type: string
                  cookieEnabled:
                    type: boolean
                  href:
                    type: string
                  innerHeight:
                    type: integer
                  innerWidth:
                    type: integer
                  scrollX:
                    type: integer
                  scrollY:
                    type: integer
                  timeStamp:
                    type: integer
                    description: Unix Timestamp (milliseconds)
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onclick:
    post:
      summary: Collecting OnClick event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onscroll:
    post:
      summary: Collecting OnScroll event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onapicall:
    post:
      summary: Collecting OnApiCall event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
            required:
              - method
              - url
            properties:
              method:
                type: string
                enum:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
              url:
                type: string
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  InitInformation:
    type: object
    required:
      - customerCode
      - userIdentity
    properties:
      customerCode:
        type: string
        description: customer code
      userIdentity:
        type: object
        description: user identity of device and user
        properties:
          deviceCode:
            type: string
            description: device cookie
          hashedUserId:
            type: string
            description: hashed user id (unique)
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
