swagger: '2.0'
info:
  version: "1.1.0"
  title: Project Artemis
  description: collector + feature toggle
host: interact.com
basePath: /api
produces:
  - application/json
paths:
  /init:
    post:
      parameters:
        - name: initInformation
          in: body
          required: true
          schema:
            type: object
            properties:
              customerCode:
                type: string
              hashedUserId:
                type: string
      responses:
        200:
          schema:
            type: object
            properties:
              featuresConfig:
                type: array
                items:
                  type: object
                  properties:
                    featureName:
                      type: string
                    featureType:
                      type: string
              code:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onload:
    post:
      summary: Get config for client side and collecting OnLoad event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
            required:
              - ic
              - eventData
            properties:
              uid:
                type: string
                description: unique user id
              ic:
                type: string
                description: identity code
              eventData:
                type: object
                description: data from browser onload event
                properties:
                  appCodeName:
                    type: string
                  appName:
                    type: string
                  appVersion:
                    type: string
                  cookieEnabled:
                    type: boolean
                  href:
                    type: string
                  innerHeight:
                    type: integer
                  innerWidth:
                    type: integer
                  scrollX:
                    type: integer
                  scrollY:
                    type: integer
                  timeStamp:
                    type: integer
                    description: Unix Timestamp (milliseconds)
      responses:
        200:
          description: Success
          type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onclick:
    post:
      summary: Collecting OnClick event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onscroll:
    post:
      summary: Collecting OnScroll event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /event/onapicall:
    post:
      summary: Collecting OnApiCall event from browser
      parameters:
        - name: rawData
          in: body
          required: true
          schema:
            type: object
            required:
              - method
              - url
            properties:
              method:
                type: string
                enum:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
              url:
                type: string
      responses:
        200:
          description: Success
          schema:
            type: object
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  ConfigResponse:
    type: object
    required:
      - uid
      - enabledFeatures
    properties:
      uid:
        type: string
        description: unique user id
      enabledFeatures:
        type: array
        description: list of enabled features
        items:
          type: object
          description: dom element attributes
          properties:
            name:
              type: string
              description: feature name
            type:
              type: string
              description: feature type to be enabled
              enum:
                - A
                - B
                - default
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
